// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCoreAPIYFrontBlazor.Server.Persistence;

#nullable disable

namespace NetCoreAPIYFrontBlazor.Server.Persistence.Migrations
{
    [DbContext(typeof(ServerContext))]
    [Migration("20250801124706_Modif_InputDataHVTapPosMax")]
    partial class Modif_InputDataHVTapPosMax
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("NetCoreAPIYFrontBlazor.Server.Domain.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CampoModificado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntidadModificada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntidadModificadaId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("NetCoreAPIYFrontBlazor.Server.Domain.InputData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cooling")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Customer")
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("Frecc")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("HVTapNegMin")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("HVTapNegNumero")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("HVTapNegRegulacion")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("HVTapPosMax")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("HVTapPosNumero")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("HVTapPosRegulacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("OilKind")
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Project")
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("TransformadorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TransformadorId")
                        .IsUnique();

                    b.ToTable("InputsData");
                });

            modelBuilder.Entity("NetCoreAPIYFrontBlazor.Server.Domain.Transformador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detalle")
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .IsFixedLength();

                    b.Property<string>("Referencia")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("Transformadores");
                });

            modelBuilder.Entity("NetCoreAPIYFrontBlazor.Server.Domain.InputData", b =>
                {
                    b.HasOne("NetCoreAPIYFrontBlazor.Server.Domain.Transformador", "Transformador")
                        .WithOne("InputData")
                        .HasForeignKey("NetCoreAPIYFrontBlazor.Server.Domain.InputData", "TransformadorId");

                    b.Navigation("Transformador");
                });

            modelBuilder.Entity("NetCoreAPIYFrontBlazor.Server.Domain.Transformador", b =>
                {
                    b.Navigation("InputData");
                });
#pragma warning restore 612, 618
        }
    }
}
