// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCoreAPIYFrontBlazor.Server.Persistence;

#nullable disable

namespace NetCoreAPIYFrontBlazor.Server.Persistence.Migrations
{
    [DbContext(typeof(ServerContext))]
    [Migration("20260212093421_Alta_HiVoltage")]
    partial class Alta_HiVoltage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("NetCoreAPIYFrontBlazor.Server.Domain.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CampoModificado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntidadModificada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntidadModificadaId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("NetCoreAPIYFrontBlazor.Server.Domain.HiVoltage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("NudeCond")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("NudeCondGrossWire")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int?>("ParallCondGrossWireMax")
                        .HasColumnType("int");

                    b.Property<int?>("ParallCondGrossWireMin")
                        .HasColumnType("int");

                    b.Property<int?>("ParallCondMax")
                        .HasColumnType("int");

                    b.Property<int?>("ParallCondMin")
                        .HasColumnType("int");

                    b.Property<int?>("StripSizeMax")
                        .HasColumnType("int");

                    b.Property<int?>("StripSizeMin")
                        .HasColumnType("int");

                    b.Property<int?>("TransformadorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Wire")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TransformadorId");

                    b.ToTable("HiVoltages");
                });

            modelBuilder.Entity("NetCoreAPIYFrontBlazor.Server.Domain.InputData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Altitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConectionHV1")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ConectionLV1")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ConectionVacio2")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Cooling")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Customer")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Designer")
                        .HasColumnType("varchar(40)");

                    b.Property<int?>("Foils")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Frecc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HVBIL")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("HVKIND")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("HVMAT")
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("HVTapNegMin")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("HVTapNegNumero")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("HVTapNegRegulacion")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("HVTapPosMax")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("HVTapPosNumero")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("HVTapPosRegulacion")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KRAB")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KRBT")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LVBIL")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("LVKIND")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("LVMAT")
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("LineVoltGuion")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LineVoltHV1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LineVoltLV1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LineVoltVacio")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LineVoltVacio2")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Llosses")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NLLosses")
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("Noise")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NoiseKHi")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("NoiseKP")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("NoiseKSB")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("NoiseKV")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("OFNum")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("OilKind")
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Project")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Rev")
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("SC")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Standard")
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("TMax")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TransformadorId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TurnsLV1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TransformadorId")
                        .IsUnique();

                    b.ToTable("InputsData");
                });

            modelBuilder.Entity("NetCoreAPIYFrontBlazor.Server.Domain.Transformador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detalle")
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .IsFixedLength();

                    b.Property<string>("Referencia")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("Transformadores");
                });

            modelBuilder.Entity("NetCoreAPIYFrontBlazor.Server.Domain.HiVoltage", b =>
                {
                    b.HasOne("NetCoreAPIYFrontBlazor.Server.Domain.Transformador", "Transformador")
                        .WithMany()
                        .HasForeignKey("TransformadorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Transformador");
                });

            modelBuilder.Entity("NetCoreAPIYFrontBlazor.Server.Domain.InputData", b =>
                {
                    b.HasOne("NetCoreAPIYFrontBlazor.Server.Domain.Transformador", "Transformador")
                        .WithOne("InputData")
                        .HasForeignKey("NetCoreAPIYFrontBlazor.Server.Domain.InputData", "TransformadorId");

                    b.Navigation("Transformador");
                });

            modelBuilder.Entity("NetCoreAPIYFrontBlazor.Server.Domain.Transformador", b =>
                {
                    b.Navigation("InputData");
                });
#pragma warning restore 612, 618
        }
    }
}
